- name: Check bootstrap node already configured
  ansible.builtin.shell:
    cmd: incus admin cluster list-database
  register: incus_cluster_list_database

- name: Configure bootstrap node
  when: 
  - hostvars[inventory_hostname].internal_host not in incus_cluster_list_database.stdout
  - inventory_hostname in groups["bootstrap"]
  block:
  - name: Check bootstrap node config exists
    ansible.builtin.stat: 
      path: "{{ incus.dir }}/bootstrap.yml"
    register: bootstrap_node_config

  - name: Copy bootstrap node config
    ansible.builtin.template:
      src: bootstrap.yml.j2
      dest: "{{ incus.dir }}/bootstrap.yml"
    when: not bootstrap_node_config.stat.exists

  - name: Init bootstrap node
    ansible.builtin.shell:
      cmd: incus admin init --preseed < {{ incus.dir }}/bootstrap.yml 

- name: Init members
  ansible.builtin.include_tasks: init_member.yml
  vars:
    member:
      name: "{{ current_member }}"
      address: "{{ hostvars[current_member].internal_host }}"
  with_items: "{{ groups['members'] }}"
  loop_control:
    loop_var: current_member
  when: inventory_hostname in groups["bootstrap"]

- name: Check instance image already imported
  ansible.builtin.shell:
    cmd: incus image list
  register: incus_image_list
    
- name: Import instance image
  when: 
  - not incus_image_list.stdout is search("hogwarts-cloud-image")
  - inventory_hostname in groups["bootstrap"]
  block:
  - name: Check image archive exists
    ansible.builtin.stat: 
      path: "{{ incus.dir }}/incus.tar.xz"
    register: image_archive
  
  - name: Copy image archive
    ansible.builtin.copy:
      src: "{{ role_path }}/files/incus.tar.xz"
      dest: "{{ incus.dir }}/incus.tar.xz"
    when: not image_archive.stat.exists
      
  - name: Check rootfs exists
    ansible.builtin.stat: 
      path: "{{ incus.dir }}/rootfs.squashfs"
    register: rootfs
  
  - name: Copy rootfs
    ansible.builtin.copy:
      src: "{{ role_path }}/files/rootfs.squashfs"
      dest: "{{ incus.dir }}/rootfs.squashfs"
    when: not rootfs.stat.exists

  - name: Import instance image
    ansible.builtin.shell:
      cmd: incus image import {{ incus.dir }}/incus.tar.xz {{ incus.dir }}/rootfs.squashfs --alias hogwarts-cloud-image 
