incus:
  dir: /etc/incus
  apt_repository:
    path: /etc/apt/sources.list.d/zabbly-incus-stable.sources
    public_key:
      path: /etc/apt/keyrings/zabbly.asc
      fingerprint: "4EFC 5906 96CB 15B8 7C73  A3AD 82CC 8797 C838 DCFD"
  cluster:
    lvm:
      vg: vms
      lv: IncusThinPool 
    bridge: vmbr
    image: hogwarts-cloud-image
