- hosts: all
  remote_user: debian
  become: true
  tasks:
  - name: Enable root login
    ansible.builtin.lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: "PermitRootLogin yes"
      state: present
  
  - name: Copy key
    ansible.builtin.copy:
      src: /home/debian/.ssh/authorized_keys
      dest: /root/.ssh/authorized_keys
      remote_src: true

  - name: Restart sshd
    ansible.builtin.service:
      name: sshd
      state: restarted

  - name: Reset ssh connection
    meta: reset_connection